[package]
name = "hyper-chunky"
version = "0.1.0"
authors = ["Chris West (Faux) <git@goeswhere.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
env_logger = "0.7"
failure = "0.1"
futures = "0.1"
hyper = "0.12"
log = "0.4"
